### ISSUE TITLE
Store movie models in MySQL database

### ISSUE THREAD

**Issue by macbre** [macbre/vita#17]
```yaml
version: '2'
services:
  # metrics storage
  db:
    image: mysql:8.0
    volumes:
      - ./datadir:/var/lib/mysql
    environment:
    # https://hub.docker.com/_/mysql
    - MYSQL_ROOT_PASSWORD=552c0ba71b1046a083583ebf943cc9aa09f39a32
    - MYSQL_DATABASE=vita
    - MYSQL_USER=vita
    - MYSQL_PASSWORD=07064fd15da6cb49f193be2fd2b107a97eb9aab0
    restart: always
```
